
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ifit?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 894833959
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.ifit.entity
  mapper-locations: classpath:mapping/*.xml

server:
  port: 8080
  address: 0.0.0.0
